/**
 * Last generated by Dialog Designer at: 2006-JUN-20  02:10:12 PM
 */
package english.prompts;

public class extncannotreached extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for extncannotreached.
	 */
	public extncannotreached() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2019-AUG-29  10:01:53 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("extncannotreached");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.TEXT,"The extension number", null));

		format = new com.avaya.sce.runtime.Format();
		format.add(com.avaya.sce.runtime.Format.FORMAT,com.avaya.sce.runtime.Format.FMT_TEXT);
		add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.VARIABLE_TEXT,"collectdigits:value", format));

		if ( new com.avaya.sce.runtime.Condition( "condition", "transfertoextn:state", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "busy", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.TEXT,"is busy", null));
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "transfertoextn:state", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "failed", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.TEXT,"could not reached. call operation failed.", null));
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "transfertoextn:state", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "noanswer", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.TEXT,"is not answering", null));
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "transfertoextn:state", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "unreachable", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.TEXT,"is unreachable", null));
		}
		if ( new com.avaya.sce.runtime.Condition( "condition", "transfertoextn:state", com.avaya.sce.runtime.Expression.STRING_EQUAL_IGNORE, "unknown", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.TEXT,"could not be reached due to an unknown error", null));
		}

	}}
